window.onload = function () {

 

  //================= data structure =================
  // in this object list we save all detail about users.

  let users = [
    {
      fullName: "defaultadmin",
      userName: "adminadmin",
      email: "adminemail",
      phoneNo: 0771234567,
      password: "adminadmin",
    } // test account credentials
  ];


  // ================ sign-in page js ===================
  //this code block save sign-in data to "users" objectif 
  //data save in browser local storage
  
  if (document.getElementById("form")) {
    let myForm = document.getElementById("form");
    myForm.addEventListener("submit", function (event) {
        console.log("submit triggerd");
        event.preventDefault(); // prevent default form submission behavior. stop been submit since there is no backend

        //save data to "obj" object
        let fName = document.getElementById("fullName").value;
        let uName = document.getElementById("userName").value;
        let email2 = document.getElementById("email").value;
        let pNumber = document.getElementById("phoneNumber").value;
        let pass = document.getElementById("password").value;
        obj = {
            fullName: fName,
            userName: uName,
            email: email2,
            phoneNo: pNumber,
            password: pass,
          };
        //append "obj" to "users"
        users.push(obj);
        //save data in browser local storage
        localStorage.setItem("users", JSON.stringify(users));
        console.log(users);
        window.location.href = "./login.html";
        console.log(users);
    });
  }

  // ================ login page js ===================
  //this cord block check if input data matche to the user array data
  if (document.getElementById("login-button")) { //without this if condition errors occures. 
    document.getElementById("login-button").addEventListener("click", function () {
        //get values
        let loginUserName = document.getElementById("loginUserName").value;
        let loginPassword = document.getElementById("loginPassword").value;
  
        //retrive from stored data in browser local storage
        let storedUsers = JSON.parse(localStorage.getItem("users"));
        console.log(storedUsers);

        //check if storedUsers object contains the user name.
        //if username found. then check password.
        //if username and password matches, user redirect to ticketing page
        let isMatchUserNamePass = false; 
        for (let i = 0; i < storedUsers.length; i++) {
          console.log("for loop " + i);
          if (loginUserName == storedUsers[i].userName) {
            if (loginPassword == storedUsers[i].password) {
            isMatchUserNamePass = true;
              window.location.href = "./ticketing.html";
            };
          };
        };

        //if user inputs not matchs, then this error pops
        if(!isMatchUserNamePass){
            alert("User name or password is wrong!");
        };
        
      });
  };

  // =========================================================================
  // =================== BUS data for ticketing.html =========================
  // =========================================================================

  const kandyColombo = {
    bustList:[
      {
        busName : "Pink Queen",
        StartTime : "7.00AM",
        EndTime : "10.00AM",
        Status : "AC bus",
        Seats : 52,
        RegNumber : "NA-2020",
        SeatDetails : [
          { seatNo: "s1", isClicked: false, status: "booked" },
          { seatNo: "s2", isClicked: false, status: "not-booked" },
          { seatNo: "s3", isClicked: false, status: "booked" },
          { seatNo: "s4", isClicked: false, status: "not-booked" },
          { seatNo: "s5", isClicked: false, status: "booked" },
          { seatNo: "s6", isClicked: false, status: "booked" },
          { seatNo: "s7", isClicked: false, status: "booked" },
          { seatNo: "s8", isClicked: false, status: "booked" },
          { seatNo: "s9", isClicked: false, status: "booked" },
          { seatNo: "s10", isClicked: false, status: "not-booked" },
          { seatNo: "s11", isClicked: false, status: "booked" },
          { seatNo: "s12", isClicked: false, status: "booked" },
          { seatNo: "s13", isClicked: false, status: "not-booked" },
          { seatNo: "s14", isClicked: false, status: "booked" },
          { seatNo: "s15", isClicked: false, status: "booked" },
          { seatNo: "s16", isClicked: false, status: "not-booked" },
          { seatNo: "s17", isClicked: false, status: "not-booked" },
          { seatNo: "s18", isClicked: false, status: "booked" },
          { seatNo: "s19", isClicked: false, status: "booked" },
          { seatNo: "s20", isClicked: false, status: "not-booked" },
          { seatNo: "s21", isClicked: false, status: "booked" },
          { seatNo: "s22", isClicked: false, status: "booked" },
          { seatNo: "s23", isClicked: false, status: "booked" },
          { seatNo: "s24", isClicked: false, status: "booked" },
          { seatNo: "s25", isClicked: false, status: "not-booked" },
          { seatNo: "s26", isClicked: false, status: "not-booked" },
          { seatNo: "s27", isClicked: false, status: "not-booked" },
          { seatNo: "s28", isClicked: false, status: "booked" },
          { seatNo: "s29", isClicked: false, status: "booked" },
          { seatNo: "s30", isClicked: false, status: "not-booked" },
          { seatNo: "s31", isClicked: false, status: "booked" },
          { seatNo: "s32", isClicked: false, status: "booked" },
          { seatNo: "s33", isClicked: false, status: "not-booked" },
          { seatNo: "s34", isClicked: false, status: "booked" },
          { seatNo: "s35", isClicked: false, status: "not-booked" },
          { seatNo: "s36", isClicked: false, status: "not-booked" },
          { seatNo: "s37", isClicked: false, status: "booked" },
          { seatNo: "s38", isClicked: false, status: "booked" },
          { seatNo: "s39", isClicked: false, status: "booked" },
          { seatNo: "s40", isClicked: false, status: "not-booked" },
          { seatNo: "s41", isClicked: false, status: "booked" },
          { seatNo: "s42", isClicked: false, status: "booked" },
          { seatNo: "s43", isClicked: false, status: "not-booked" },
          { seatNo: "s44", isClicked: false, status: "booked" },
          { seatNo: "s45", isClicked: false, status: "not-booked" },
          { seatNo: "s46", isClicked: false, status: "not-booked" },
          { seatNo: "s47", isClicked: false, status: "booked" },
          { seatNo: "s48", isClicked: false, status: "booked" },
          { seatNo: "s49", isClicked: false, status: "booked" },
          { seatNo: "s50", isClicked: false, status: "booked" },
          { seatNo: "s51", isClicked: false, status: "booked" },
          { seatNo: "s52", isClicked: false, status: "booked" },
        ],
      },
      {
        busName : "Crazy Runner",
        StartTime : "12.00PM",
        EndTime : "03.30PM",
        Status : "Semi-luxury",
        Seats : 52,
        RegNumber : "NA-9356",
        SeatDetails : [
          { seatNo: "s1", isClicked: false, status: "booked" },
          { seatNo: "s2", isClicked: false, status: "not-booked" },
          { seatNo: "s3", isClicked: false, status: "booked" },
          { seatNo: "s4", isClicked: false, status: "not-booked" },
          { seatNo: "s5", isClicked: false, status: "booked" },
          { seatNo: "s6", isClicked: false, status: "booked" },
          { seatNo: "s7", isClicked: false, status: "booked" },
          { seatNo: "s8", isClicked: false, status: "booked" },
          { seatNo: "s9", isClicked: false, status: "booked" },
          { seatNo: "s10", isClicked: false, status: "not-booked" },
          { seatNo: "s11", isClicked: false, status: "booked" },
          { seatNo: "s12", isClicked: false, status: "not-booked" },
          { seatNo: "s13", isClicked: false, status: "not-booked" },
          { seatNo: "s14", isClicked: false, status: "booked" },
          { seatNo: "s15", isClicked: false, status: "booked" },
          { seatNo: "s16", isClicked: false, status: "not-booked" },
          { seatNo: "s17", isClicked: false, status: "not-booked" },
          { seatNo: "s18", isClicked: false, status: "booked" },
          { seatNo: "s19", isClicked: false, status: "not-booked" },
          { seatNo: "s20", isClicked: false, status: "booked" },
          { seatNo: "s21", isClicked: false, status: "booked" },
          { seatNo: "s22", isClicked: false, status: "booked" },
          { seatNo: "s23", isClicked: false, status: "not-booked" },
          { seatNo: "s24", isClicked: false, status: "booked" },
          { seatNo: "s25", isClicked: false, status: "not-booked" },
          { seatNo: "s26", isClicked: false, status: "not-booked" },
          { seatNo: "s27", isClicked: false, status: "not-booked" },
          { seatNo: "s28", isClicked: false, status: "booked" },
          { seatNo: "s29", isClicked: false, status: "booked" },
          { seatNo: "s30", isClicked: false, status: "not-booked" },
          { seatNo: "s31", isClicked: false, status: "booked" },
          { seatNo: "s32", isClicked: false, status: "booked" },
          { seatNo: "s33", isClicked: false, status: "not-booked" },
          { seatNo: "s34", isClicked: false, status: "booked" },
          { seatNo: "s35", isClicked: false, status: "not-booked" },
          { seatNo: "s36", isClicked: false, status: "not-booked" },
          { seatNo: "s37", isClicked: false, status: "booked" },
          { seatNo: "s38", isClicked: false, status: "booked" },
          { seatNo: "s39", isClicked: false, status: "booked" },
          { seatNo: "s40", isClicked: false, status: "not-booked" },
          { seatNo: "s41", isClicked: false, status: "booked" },
          { seatNo: "s42", isClicked: false, status: "booked" },
          { seatNo: "s43", isClicked: false, status: "not-booked" },
          { seatNo: "s44", isClicked: false, status: "booked" },
          { seatNo: "s45", isClicked: false, status: "not-booked" },
          { seatNo: "s46", isClicked: false, status: "not-booked" },
          { seatNo: "s47", isClicked: false, status: "booked" },
          { seatNo: "s48", isClicked: false, status: "booked" },
          { seatNo: "s49", isClicked: false, status: "booked" },
          { seatNo: "s50", isClicked: false, status: "booked" },
          { seatNo: "s51", isClicked: false, status: "not-booked" },
          { seatNo: "s52", isClicked: false, status: "not-booked" },
        ],
      },
      {
        busName : "AWS Transport",
        StartTime : "7.45PM",
        EndTime : "10.00PM",
        Status : "Normal Price",
        Seats : 32,
        RegNumber : "NB-9020",
        SeatDetails : [
          { seatNo: "ss1", isClicked: false, status: "booked" },
          { seatNo: "ss2", isClicked: false, status: "not-booked" },
          { seatNo: "ss3", isClicked: false, status: "booked" },
          { seatNo: "ss4", isClicked: false, status: "not-booked" },
          { seatNo: "ss5", isClicked: false, status: "booked" },
          { seatNo: "ss6", isClicked: false, status: "not-booked" },
          { seatNo: "ss7", isClicked: false, status: "booked" },
          { seatNo: "ss8", isClicked: false, status: "booked" },
          { seatNo: "ss9", isClicked: false, status: "booked" },
          { seatNo: "ss10", isClicked: false, status: "booked" },
          { seatNo: "ss11", isClicked: false, status: "booked" },
          { seatNo: "ss12", isClicked: false, status: "booked" },
          { seatNo: "ss13", isClicked: false, status: "not-booked" },
          { seatNo: "ss14", isClicked: false, status: "booked" },
          { seatNo: "ss15", isClicked: false, status: "booked" },
          { seatNo: "ss16", isClicked: false, status: "not-booked" },
          { seatNo: "ss17", isClicked: false, status: "booked" },
          { seatNo: "ss18", isClicked: false, status: "booked" },
          { seatNo: "ss19", isClicked: false, status: "booked" },
          { seatNo: "ss20", isClicked: false, status: "not-booked" },
          { seatNo: "ss21", isClicked: false, status: "booked" },
          { seatNo: "ss22", isClicked: false, status: "booked" },
          { seatNo: "ss23", isClicked: false, status: "booked" },
          { seatNo: "ss24", isClicked: false, status: "booked" },
          { seatNo: "ss25", isClicked: false, status: "not-booked" },
          { seatNo: "ss26", isClicked: false, status: "not-booked" },
          { seatNo: "ss27", isClicked: false, status: "not-booked" },
          { seatNo: "ss28", isClicked: false, status: "booked" },
          { seatNo: "ss29", isClicked: false, status: "booked" },
          { seatNo: "ss30", isClicked: false, status: "not-booked" },
          { seatNo: "ss31", isClicked: false, status: "booked" },
          { seatNo: "ss32", isClicked: false, status: "booked" },
        ],
      },
    ]
  };

  const kandyGalle = {
    bustList:[
      {
        busName : "Golden Bird",
        StartTime : "6.00AM",
        EndTime : "12.30AM",
        Status : "AC bus",
        Seats : 52,
        RegNumber : "NA-0920",
        SeatDetails : [
          { seatNo: "s1", isClicked: false, status: "booked" },
          { seatNo: "s2", isClicked: false, status: "not-booked" },
          { seatNo: "s3", isClicked: false, status: "booked" },
          { seatNo: "s4", isClicked: false, status: "not-booked" },
          { seatNo: "s5", isClicked: false, status: "booked" },
          { seatNo: "s6", isClicked: false, status: "booked" },
          { seatNo: "s7", isClicked: false, status: "booked" },
          { seatNo: "s8", isClicked: false, status: "booked" },
          { seatNo: "s9", isClicked: false, status: "booked" },
          { seatNo: "s10", isClicked: false, status: "not-booked" },
          { seatNo: "s11", isClicked: false, status: "booked" },
          { seatNo: "s12", isClicked: false, status: "booked" },
          { seatNo: "s13", isClicked: false, status: "not-booked" },
          { seatNo: "s14", isClicked: false, status: "booked" },
          { seatNo: "s15", isClicked: false, status: "booked" },
          { seatNo: "s16", isClicked: false, status: "not-booked" },
          { seatNo: "s17", isClicked: false, status: "not-booked" },
          { seatNo: "s18", isClicked: false, status: "booked" },
          { seatNo: "s19", isClicked: false, status: "booked" },
          { seatNo: "s20", isClicked: false, status: "not-booked" },
          { seatNo: "s21", isClicked: false, status: "booked" },
          { seatNo: "s22", isClicked: false, status: "booked" },
          { seatNo: "s23", isClicked: false, status: "booked" },
          { seatNo: "s24", isClicked: false, status: "booked" },
          { seatNo: "s25", isClicked: false, status: "not-booked" },
          { seatNo: "s26", isClicked: false, status: "not-booked" },
          { seatNo: "s27", isClicked: false, status: "not-booked" },
          { seatNo: "s28", isClicked: false, status: "booked" },
          { seatNo: "s29", isClicked: false, status: "booked" },
          { seatNo: "s30", isClicked: false, status: "not-booked" },
          { seatNo: "s31", isClicked: false, status: "booked" },
          { seatNo: "s32", isClicked: false, status: "booked" },
          { seatNo: "s33", isClicked: false, status: "not-booked" },
          { seatNo: "s34", isClicked: false, status: "booked" },
          { seatNo: "s35", isClicked: false, status: "not-booked" },
          { seatNo: "s36", isClicked: false, status: "not-booked" },
          { seatNo: "s37", isClicked: false, status: "booked" },
          { seatNo: "s38", isClicked: false, status: "booked" },
          { seatNo: "s39", isClicked: false, status: "booked" },
          { seatNo: "s40", isClicked: false, status: "not-booked" },
          { seatNo: "s41", isClicked: false, status: "booked" },
          { seatNo: "s42", isClicked: false, status: "booked" },
          { seatNo: "s43", isClicked: false, status: "not-booked" },
          { seatNo: "s44", isClicked: false, status: "booked" },
          { seatNo: "s45", isClicked: false, status: "not-booked" },
          { seatNo: "s46", isClicked: false, status: "not-booked" },
          { seatNo: "s47", isClicked: false, status: "booked" },
          { seatNo: "s48", isClicked: false, status: "booked" },
          { seatNo: "s49", isClicked: false, status: "booked" },
          { seatNo: "s50", isClicked: false, status: "booked" },
          { seatNo: "s51", isClicked: false, status: "booked" },
          { seatNo: "s52", isClicked: false, status: "booked" },
        ],
      },
      {
        busName : "Red Rose",
        StartTime : "12.00PM",
        EndTime : "6.00PM",
        Status : "Semi-luxury",
        Seats : 52,
        RegNumber : "NC-8356",
        SeatDetails : [
          { seatNo: "s1", isClicked: false, status: "booked" },
          { seatNo: "s2", isClicked: false, status: "not-booked" },
          { seatNo: "s3", isClicked: false, status: "booked" },
          { seatNo: "s4", isClicked: false, status: "not-booked" },
          { seatNo: "s5", isClicked: false, status: "booked" },
          { seatNo: "s6", isClicked: false, status: "booked" },
          { seatNo: "s7", isClicked: false, status: "booked" },
          { seatNo: "s8", isClicked: false, status: "booked" },
          { seatNo: "s9", isClicked: false, status: "booked" },
          { seatNo: "s10", isClicked: false, status: "not-booked" },
          { seatNo: "s11", isClicked: false, status: "booked" },
          { seatNo: "s12", isClicked: false, status: "not-booked" },
          { seatNo: "s13", isClicked: false, status: "not-booked" },
          { seatNo: "s14", isClicked: false, status: "booked" },
          { seatNo: "s15", isClicked: false, status: "booked" },
          { seatNo: "s16", isClicked: false, status: "not-booked" },
          { seatNo: "s17", isClicked: false, status: "not-booked" },
          { seatNo: "s18", isClicked: false, status: "booked" },
          { seatNo: "s19", isClicked: false, status: "not-booked" },
          { seatNo: "s20", isClicked: false, status: "booked" },
          { seatNo: "s21", isClicked: false, status: "booked" },
          { seatNo: "s22", isClicked: false, status: "booked" },
          { seatNo: "s23", isClicked: false, status: "not-booked" },
          { seatNo: "s24", isClicked: false, status: "booked" },
          { seatNo: "s25", isClicked: false, status: "not-booked" },
          { seatNo: "s26", isClicked: false, status: "not-booked" },
          { seatNo: "s27", isClicked: false, status: "not-booked" },
          { seatNo: "s28", isClicked: false, status: "booked" },
          { seatNo: "s29", isClicked: false, status: "booked" },
          { seatNo: "s30", isClicked: false, status: "not-booked" },
          { seatNo: "s31", isClicked: false, status: "booked" },
          { seatNo: "s32", isClicked: false, status: "booked" },
          { seatNo: "s33", isClicked: false, status: "not-booked" },
          { seatNo: "s34", isClicked: false, status: "booked" },
          { seatNo: "s35", isClicked: false, status: "not-booked" },
          { seatNo: "s36", isClicked: false, status: "not-booked" },
          { seatNo: "s37", isClicked: false, status: "booked" },
          { seatNo: "s38", isClicked: false, status: "booked" },
          { seatNo: "s39", isClicked: false, status: "booked" },
          { seatNo: "s40", isClicked: false, status: "not-booked" },
          { seatNo: "s41", isClicked: false, status: "booked" },
          { seatNo: "s42", isClicked: false, status: "booked" },
          { seatNo: "s43", isClicked: false, status: "not-booked" },
          { seatNo: "s44", isClicked: false, status: "booked" },
          { seatNo: "s45", isClicked: false, status: "not-booked" },
          { seatNo: "s46", isClicked: false, status: "not-booked" },
          { seatNo: "s47", isClicked: false, status: "booked" },
          { seatNo: "s48", isClicked: false, status: "booked" },
          { seatNo: "s49", isClicked: false, status: "booked" },
          { seatNo: "s50", isClicked: false, status: "booked" },
          { seatNo: "s51", isClicked: false, status: "not-booked" },
          { seatNo: "s52", isClicked: false, status: "not-booked" },
        ],
      },
      {
        busName : "Blue Diamond",
        StartTime : "7.40PM",
        EndTime : "11.30PM",
        Status : "Normal Price",
        Seats : 32,
        RegNumber : "NB-3421",
        SeatDetails : [
          { seatNo: "ss1", isClicked: false, status: "booked" },
          { seatNo: "ss2", isClicked: false, status: "not-booked" },
          { seatNo: "ss3", isClicked: false, status: "booked" },
          { seatNo: "ss4", isClicked: false, status: "not-booked" },
          { seatNo: "ss5", isClicked: false, status: "booked" },
          { seatNo: "ss6", isClicked: false, status: "not-booked" },
          { seatNo: "ss7", isClicked: false, status: "booked" },
          { seatNo: "ss8", isClicked: false, status: "booked" },
          { seatNo: "ss9", isClicked: false, status: "booked" },
          { seatNo: "ss10", isClicked: false, status: "booked" },
          { seatNo: "ss11", isClicked: false, status: "booked" },
          { seatNo: "ss12", isClicked: false, status: "booked" },
          { seatNo: "ss13", isClicked: false, status: "booked" },
          { seatNo: "ss14", isClicked: false, status: "booked" },
          { seatNo: "ss15", isClicked: false, status: "booked" },
          { seatNo: "ss16", isClicked: false, status: "not-booked" },
          { seatNo: "ss17", isClicked: false, status: "booked" },
          { seatNo: "ss18", isClicked: false, status: "booked" },
          { seatNo: "ss19", isClicked: false, status: "booked" },
          { seatNo: "ss20", isClicked: false, status: "not-booked" },
          { seatNo: "ss21", isClicked: false, status: "booked" },
          { seatNo: "ss22", isClicked: false, status: "booked" },
          { seatNo: "ss23", isClicked: false, status: "booked" },
          { seatNo: "ss24", isClicked: false, status: "not-booked" },
          { seatNo: "ss25", isClicked: false, status: "booked" },
          { seatNo: "ss26", isClicked: false, status: "not-booked" },
          { seatNo: "ss27", isClicked: false, status: "booked" },
          { seatNo: "ss28", isClicked: false, status: "not-booked" },
          { seatNo: "ss29", isClicked: false, status: "booked" },
          { seatNo: "ss30", isClicked: false, status: "booked" },
          { seatNo: "ss31", isClicked: false, status: "booked" },
          { seatNo: "ss32", isClicked: false, status: "booked" },
        ],
      },
    ]
  };

  const JaffnaGalle = {
    bustList:[
      {
        busName : "Green Star",
        StartTime : "5.30AM",
        EndTime : "2.30PM",
        Status : "AC bus",
        Seats : 52,
        RegNumber : "ND-0210",
        SeatDetails : [
          { seatNo: "s1", isClicked: false, status: "booked" },
          { seatNo: "s2", isClicked: false, status: "not-booked" },
          { seatNo: "s3", isClicked: false, status: "booked" },
          { seatNo: "s4", isClicked: false, status: "not-booked" },
          { seatNo: "s5", isClicked: false, status: "booked" },
          { seatNo: "s6", isClicked: false, status: "booked" },
          { seatNo: "s7", isClicked: false, status: "booked" },
          { seatNo: "s8", isClicked: false, status: "booked" },
          { seatNo: "s9", isClicked: false, status: "booked" },
          { seatNo: "s10", isClicked: false, status: "booked" },
          { seatNo: "s11", isClicked: false, status: "not-booked" },
          { seatNo: "s12", isClicked: false, status: "not-booked" },
          { seatNo: "s13", isClicked: false, status: "not-booked" },
          { seatNo: "s14", isClicked: false, status: "booked" },
          { seatNo: "s15", isClicked: false, status: "booked" },
          { seatNo: "s16", isClicked: false, status: "booked" },
          { seatNo: "s17", isClicked: false, status: "not-booked" },
          { seatNo: "s18", isClicked: false, status: "booked" },
          { seatNo: "s19", isClicked: false, status: "booked" },
          { seatNo: "s20", isClicked: false, status: "booked" },
          { seatNo: "s21", isClicked: false, status: "booked" },
          { seatNo: "s22", isClicked: false, status: "booked" },
          { seatNo: "s23", isClicked: false, status: "booked" },
          { seatNo: "s24", isClicked: false, status: "booked" },
          { seatNo: "s25", isClicked: false, status: "not-booked" },
          { seatNo: "s26", isClicked: false, status: "booked" },
          { seatNo: "s27", isClicked: false, status: "not-booked" },
          { seatNo: "s28", isClicked: false, status: "booked" },
          { seatNo: "s29", isClicked: false, status: "booked" },
          { seatNo: "s30", isClicked: false, status: "not-booked" },
          { seatNo: "s31", isClicked: false, status: "booked" },
          { seatNo: "s32", isClicked: false, status: "booked" },
          { seatNo: "s33", isClicked: false, status: "not-booked" },
          { seatNo: "s34", isClicked: false, status: "booked" },
          { seatNo: "s35", isClicked: false, status: "not-booked" },
          { seatNo: "s36", isClicked: false, status: "not-booked" },
          { seatNo: "s37", isClicked: false, status: "booked" },
          { seatNo: "s38", isClicked: false, status: "booked" },
          { seatNo: "s39", isClicked: false, status: "booked" },
          { seatNo: "s40", isClicked: false, status: "not-booked" },
          { seatNo: "s41", isClicked: false, status: "booked" },
          { seatNo: "s42", isClicked: false, status: "booked" },
          { seatNo: "s43", isClicked: false, status: "not-booked" },
          { seatNo: "s44", isClicked: false, status: "booked" },
          { seatNo: "s45", isClicked: false, status: "not-booked" },
          { seatNo: "s46", isClicked: false, status: "booked" },
          { seatNo: "s47", isClicked: false, status: "booked" },
          { seatNo: "s48", isClicked: false, status: "booked" },
          { seatNo: "s49", isClicked: false, status: "booked" },
          { seatNo: "s50", isClicked: false, status: "not-booked" },
          { seatNo: "s51", isClicked: false, status: "booked" },
          { seatNo: "s52", isClicked: false, status: "booked" },
        ],
      },
      {
        busName : "White Elephant",
        StartTime : "12.00PM",
        EndTime : "9.00PM",
        Status : "Semi-luxury",
        Seats : 52,
        RegNumber : "NC-8096",
        SeatDetails : [
          { seatNo: "s1", isClicked: false, status: "booked" },
          { seatNo: "s2", isClicked: false, status: "not-booked" },
          { seatNo: "s3", isClicked: false, status: "booked" },
          { seatNo: "s4", isClicked: false, status: "not-booked" },
          { seatNo: "s5", isClicked: false, status: "not-booked" },
          { seatNo: "s6", isClicked: false, status: "booked" },
          { seatNo: "s7", isClicked: false, status: "booked" },
          { seatNo: "s8", isClicked: false, status: "booked" },
          { seatNo: "s9", isClicked: false, status: "booked" },
          { seatNo: "s10", isClicked: false, status: "booked" },
          { seatNo: "s11", isClicked: false, status: "booked" },
          { seatNo: "s12", isClicked: false, status: "booked" },
          { seatNo: "s13", isClicked: false, status: "not-booked" },
          { seatNo: "s14", isClicked: false, status: "booked" },
          { seatNo: "s15", isClicked: false, status: "booked" },
          { seatNo: "s16", isClicked: false, status: "not-booked" },
          { seatNo: "s17", isClicked: false, status: "not-booked" },
          { seatNo: "s18", isClicked: false, status: "booked" },
          { seatNo: "s19", isClicked: false, status: "not-booked" },
          { seatNo: "s20", isClicked: false, status: "booked" },
          { seatNo: "s21", isClicked: false, status: "booked" },
          { seatNo: "s22", isClicked: false, status: "booked" },
          { seatNo: "s23", isClicked: false, status: "not-booked" },
          { seatNo: "s24", isClicked: false, status: "booked" },
          { seatNo: "s25", isClicked: false, status: "not-booked" },
          { seatNo: "s26", isClicked: false, status: "not-booked" },
          { seatNo: "s27", isClicked: false, status: "not-booked" },
          { seatNo: "s28", isClicked: false, status: "booked" },
          { seatNo: "s29", isClicked: false, status: "booked" },
          { seatNo: "s30", isClicked: false, status: "not-booked" },
          { seatNo: "s31", isClicked: false, status: "booked" },
          { seatNo: "s32", isClicked: false, status: "booked" },
          { seatNo: "s33", isClicked: false, status: "booked" },
          { seatNo: "s34", isClicked: false, status: "booked" },
          { seatNo: "s35", isClicked: false, status: "not-booked" },
          { seatNo: "s36", isClicked: false, status: "not-booked" },
          { seatNo: "s37", isClicked: false, status: "booked" },
          { seatNo: "s38", isClicked: false, status: "booked" },
          { seatNo: "s39", isClicked: false, status: "booked" },
          { seatNo: "s40", isClicked: false, status: "booked" },
          { seatNo: "s41", isClicked: false, status: "booked" },
          { seatNo: "s42", isClicked: false, status: "booked" },
          { seatNo: "s43", isClicked: false, status: "not-booked" },
          { seatNo: "s44", isClicked: false, status: "booked" },
          { seatNo: "s45", isClicked: false, status: "not-booked" },
          { seatNo: "s46", isClicked: false, status: "not-booked" },
          { seatNo: "s47", isClicked: false, status: "booked" },
          { seatNo: "s48", isClicked: false, status: "booked" },
          { seatNo: "s49", isClicked: false, status: "booked" },
          { seatNo: "s50", isClicked: false, status: "booked" },
          { seatNo: "s51", isClicked: false, status: "not-booked" },
          { seatNo: "s52", isClicked: false, status: "not-booked" },
        ],
      },
      {
        busName : "Happy Journey",
        StartTime : "7.40PM",
        EndTime : "4.30AM",
        Status : "Normal Price",
        Seats : 32,
        RegNumber : "NB-3421",
        SeatDetails : [
          { seatNo: "ss1", isClicked: false, status: "booked" },
          { seatNo: "ss2", isClicked: false, status: "not-booked" },
          { seatNo: "ss3", isClicked: false, status: "booked" },
          { seatNo: "ss4", isClicked: false, status: "not-booked" },
          { seatNo: "ss5", isClicked: false, status: "booked" },
          { seatNo: "ss6", isClicked: false, status: "not-booked" },
          { seatNo: "ss7", isClicked: false, status: "booked" },
          { seatNo: "ss8", isClicked: false, status: "booked" },
          { seatNo: "ss9", isClicked: false, status: "booked" },
          { seatNo: "ss10", isClicked: false, status: "booked" },
          { seatNo: "ss11", isClicked: false, status: "not-booked" },
          { seatNo: "ss12", isClicked: false, status: "not-booked" },
          { seatNo: "ss13", isClicked: false, status: "not-booked" },
          { seatNo: "ss14", isClicked: false, status: "not-booked" },
          { seatNo: "ss15", isClicked: false, status: "booked" },
          { seatNo: "ss16", isClicked: false, status: "not-booked" },
          { seatNo: "ss17", isClicked: false, status: "booked" },
          { seatNo: "ss18", isClicked: false, status: "booked" },
          { seatNo: "ss19", isClicked: false, status: "booked" },
          { seatNo: "ss20", isClicked: false, status: "not-booked" },
          { seatNo: "ss21", isClicked: false, status: "booked" },
          { seatNo: "ss22", isClicked: false, status: "booked" },
          { seatNo: "ss23", isClicked: false, status: "booked" },
          { seatNo: "ss24", isClicked: false, status: "booked" },
          { seatNo: "ss25", isClicked: false, status: "not-booked" },
          { seatNo: "ss26", isClicked: false, status: "not-booked" },
          { seatNo: "ss27", isClicked: false, status: "not-booked" },
          { seatNo: "ss28", isClicked: false, status: "booked" },
          { seatNo: "ss29", isClicked: false, status: "booked" },
          { seatNo: "ss30", isClicked: false, status: "not-booked" },
          { seatNo: "ss31", isClicked: false, status: "not-booked" },
          { seatNo: "ss32", isClicked: false, status: "not-booked" },
        ],
      },
    ]
  };

  const JaffnaColombo = {
    bustList:[
      {
        busName : "Safe Travel",
        StartTime : "5.10AM",
        EndTime : "1.30PM",
        Status : "AC bus",
        Seats : 52,
        RegNumber : "ND-3865",
        SeatDetails : [
          { seatNo: "s1", isClicked: false, status: "booked" },
          { seatNo: "s2", isClicked: false, status: "not-booked" },
          { seatNo: "s3", isClicked: false, status: "booked" },
          { seatNo: "s4", isClicked: false, status: "not-booked" },
          { seatNo: "s5", isClicked: false, status: "not-booked" },
          { seatNo: "s6", isClicked: false, status: "not-booked" },
          { seatNo: "s7", isClicked: false, status: "booked" },
          { seatNo: "s8", isClicked: false, status: "booked" },
          { seatNo: "s9", isClicked: false, status: "booked" },
          { seatNo: "s10", isClicked: false, status: "not-booked" },
          { seatNo: "s11", isClicked: false, status: "booked" },
          { seatNo: "s12", isClicked: false, status: "booked" },
          { seatNo: "s13", isClicked: false, status: "not-booked" },
          { seatNo: "s14", isClicked: false, status: "booked" },
          { seatNo: "s15", isClicked: false, status: "not-booked" },
          { seatNo: "s16", isClicked: false, status: "not-booked" },
          { seatNo: "s17", isClicked: false, status: "not-booked" },
          { seatNo: "s18", isClicked: false, status: "booked" },
          { seatNo: "s19", isClicked: false, status: "booked" },
          { seatNo: "s20", isClicked: false, status: "not-booked" },
          { seatNo: "s21", isClicked: false, status: "booked" },
          { seatNo: "s22", isClicked: false, status: "booked" },
          { seatNo: "s23", isClicked: false, status: "booked" },
          { seatNo: "s24", isClicked: false, status: "booked" },
          { seatNo: "s25", isClicked: false, status: "not-booked" },
          { seatNo: "s26", isClicked: false, status: "not-booked" },
          { seatNo: "s27", isClicked: false, status: "not-booked" },
          { seatNo: "s28", isClicked: false, status: "booked" },
          { seatNo: "s29", isClicked: false, status: "booked" },
          { seatNo: "s30", isClicked: false, status: "not-booked" },
          { seatNo: "s31", isClicked: false, status: "booked" },
          { seatNo: "s32", isClicked: false, status: "booked" },
          { seatNo: "s33", isClicked: false, status: "not-booked" },
          { seatNo: "s34", isClicked: false, status: "booked" },
          { seatNo: "s35", isClicked: false, status: "not-booked" },
          { seatNo: "s36", isClicked: false, status: "not-booked" },
          { seatNo: "s37", isClicked: false, status: "booked" },
          { seatNo: "s38", isClicked: false, status: "not-booked" },
          { seatNo: "s39", isClicked: false, status: "booked" },
          { seatNo: "s40", isClicked: false, status: "not-booked" },
          { seatNo: "s41", isClicked: false, status: "booked" },
          { seatNo: "s42", isClicked: false, status: "booked" },
          { seatNo: "s43", isClicked: false, status: "not-booked" },
          { seatNo: "s44", isClicked: false, status: "booked" },
          { seatNo: "s45", isClicked: false, status: "not-booked" },
          { seatNo: "s46", isClicked: false, status: "not-booked" },
          { seatNo: "s47", isClicked: false, status: "booked" },
          { seatNo: "s48", isClicked: false, status: "booked" },
          { seatNo: "s49", isClicked: false, status: "booked" },
          { seatNo: "s50", isClicked: false, status: "booked" },
          { seatNo: "s51", isClicked: false, status: "booked" },
          { seatNo: "s52", isClicked: false, status: "booked" },
        ],
      },
      {
        busName : "Wonderful Ride",
        StartTime : "12.00PM",
        EndTime : "5.00PM",
        Status : "Semi-luxury",
        Seats : 52,
        RegNumber : "NA-8996",
        SeatDetails : [
          { seatNo: "s1", isClicked: false, status: "booked" },
          { seatNo: "s2", isClicked: false, status: "not-booked" },
          { seatNo: "s3", isClicked: false, status: "booked" },
          { seatNo: "s4", isClicked: false, status: "not-booked" },
          { seatNo: "s5", isClicked: false, status: "booked" },
          { seatNo: "s6", isClicked: false, status: "booked" },
          { seatNo: "s7", isClicked: false, status: "booked" },
          { seatNo: "s8", isClicked: false, status: "booked" },
          { seatNo: "s9", isClicked: false, status: "booked" },
          { seatNo: "s10", isClicked: false, status: "not-booked" },
          { seatNo: "s11", isClicked: false, status: "booked" },
          { seatNo: "s12", isClicked: false, status: "not-booked" },
          { seatNo: "s13", isClicked: false, status: "not-booked" },
          { seatNo: "s14", isClicked: false, status: "booked" },
          { seatNo: "s15", isClicked: false, status: "booked" },
          { seatNo: "s16", isClicked: false, status: "not-booked" },
          { seatNo: "s17", isClicked: false, status: "not-booked" },
          { seatNo: "s18", isClicked: false, status: "booked" },
          { seatNo: "s19", isClicked: false, status: "not-booked" },
          { seatNo: "s20", isClicked: false, status: "booked" },
          { seatNo: "s21", isClicked: false, status: "booked" },
          { seatNo: "s22", isClicked: false, status: "booked" },
          { seatNo: "s23", isClicked: false, status: "not-booked" },
          { seatNo: "s24", isClicked: false, status: "booked" },
          { seatNo: "s25", isClicked: false, status: "not-booked" },
          { seatNo: "s26", isClicked: false, status: "not-booked" },
          { seatNo: "s27", isClicked: false, status: "not-booked" },
          { seatNo: "s28", isClicked: false, status: "booked" },
          { seatNo: "s29", isClicked: false, status: "booked" },
          { seatNo: "s30", isClicked: false, status: "not-booked" },
          { seatNo: "s31", isClicked: false, status: "booked" },
          { seatNo: "s32", isClicked: false, status: "booked" },
          { seatNo: "s33", isClicked: false, status: "not-booked" },
          { seatNo: "s34", isClicked: false, status: "booked" },
          { seatNo: "s35", isClicked: false, status: "not-booked" },
          { seatNo: "s36", isClicked: false, status: "not-booked" },
          { seatNo: "s37", isClicked: false, status: "booked" },
          { seatNo: "s38", isClicked: false, status: "booked" },
          { seatNo: "s39", isClicked: false, status: "booked" },
          { seatNo: "s40", isClicked: false, status: "not-booked" },
          { seatNo: "s41", isClicked: false, status: "booked" },
          { seatNo: "s42", isClicked: false, status: "booked" },
          { seatNo: "s43", isClicked: false, status: "not-booked" },
          { seatNo: "s44", isClicked: false, status: "booked" },
          { seatNo: "s45", isClicked: false, status: "not-booked" },
          { seatNo: "s46", isClicked: false, status: "not-booked" },
          { seatNo: "s47", isClicked: false, status: "booked" },
          { seatNo: "s48", isClicked: false, status: "booked" },
          { seatNo: "s49", isClicked: false, status: "booked" },
          { seatNo: "s50", isClicked: false, status: "booked" },
          { seatNo: "s51", isClicked: false, status: "not-booked" },
          { seatNo: "s52", isClicked: false, status: "not-booked" },
        ],
      },
      {
        busName : "Journey of Dreams",
        StartTime : "7.50PM",
        EndTime : "3.10AM",
        Status : "Normal Price",
        Seats : 32,
        RegNumber : "NB-3421",
        SeatDetails : [
          { seatNo: "ss1", isClicked: false, status: "booked" },
          { seatNo: "ss2", isClicked: false, status: "not-booked" },
          { seatNo: "ss3", isClicked: false, status: "booked" },
          { seatNo: "ss4", isClicked: false, status: "not-booked" },
          { seatNo: "ss5", isClicked: false, status: "booked" },
          { seatNo: "ss6", isClicked: false, status: "not-booked" },
          { seatNo: "ss7", isClicked: false, status: "booked" },
          { seatNo: "ss8", isClicked: false, status: "booked" },
          { seatNo: "ss9", isClicked: false, status: "booked" },
          { seatNo: "ss10", isClicked: false, status: "not-booked" },
          { seatNo: "ss11", isClicked: false, status: "booked" },
          { seatNo: "ss12", isClicked: false, status: "booked" },
          { seatNo: "ss13", isClicked: false, status: "booked" },
          { seatNo: "ss14", isClicked: false, status: "booked" },
          { seatNo: "ss15", isClicked: false, status: "booked" },
          { seatNo: "ss16", isClicked: false, status: "not-booked" },
          { seatNo: "ss17", isClicked: false, status: "booked" },
          { seatNo: "ss18", isClicked: false, status: "booked" },
          { seatNo: "ss19", isClicked: false, status: "booked" },
          { seatNo: "ss20", isClicked: false, status: "booked" },
          { seatNo: "ss21", isClicked: false, status: "booked" },
          { seatNo: "ss22", isClicked: false, status: "booked" },
          { seatNo: "ss23", isClicked: false, status: "booked" },
          { seatNo: "ss24", isClicked: false, status: "booked" },
          { seatNo: "ss25", isClicked: false, status: "booked" },
          { seatNo: "ss26", isClicked: false, status: "booked" },
          { seatNo: "ss27", isClicked: false, status: "not-booked" },
          { seatNo: "ss28", isClicked: false, status: "booked" },
          { seatNo: "ss29", isClicked: false, status: "booked" },
          { seatNo: "ss30", isClicked: false, status: "booked" },
          { seatNo: "ss31", isClicked: false, status: "booked" },
          { seatNo: "ss32", isClicked: false, status: "booked" },
        ],
      },
    ]
  };

}; //end of document.ready()


